DROP TABLE sqlx_ledger_accounts;
DROP TABLE sqlx_ledger_journals;
DROP TABLE sqlx_ledger_tx_templates;
DROP TABLE sqlx_ledger_transactions;
DROP TABLE sqlx_ledger_entries;
DROP TABLE sqlx_ledger_balances;
DROP TABLE sqlx_ledger_current_balances;
DROP TYPE Status;
DROP TYPE DebitOrCredit;
